GET http://localhost:5000/health

#########

GET http://localhost:5000/api/menuitems

###############

POST http://localhost:5000/api/menuitems
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
    "name": "Mustamakkara",
    "price": 7.50,
    "description": "Mansesta nääs",
    "image": "tapola.jpg"
}

#############

PUT http://localhost:5000/api/menuitems/d45
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
    "name": "HK:n sininen",
    "price": 5.50,
    "description": "Suomen suosituin vihannes",
    "image": "bleu.jpg"
}

####################

DELETE http://localhost:5000/api/menuitems/d27
Authorization: BEARER {{authToken}}

########

POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
    "name": "Petter Pettersson",
    "email": "petterpettersson.com",
    "password": "pettersson1234"
}

######
# @name login
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "petter@pettersson.com",
    "password": "pettersson1234"
}

####

@authToken = {{login.response.body.token}}

######

