GET http://localhost:5000/health

#########

GET http://localhost:5000/api/menuitems

###############

POST http://localhost:5000/api/menuitems
Content-Type: application/json

{
    "price": 7.50,
    "description": "Mansesta nääs",
    "image": "tapola.jpg"
}

#############

PUT http://localhost:5000/api/menuitems/d40
Content-Type: application/json

{
    "name": "HK:n sininen",
    "price": 5.50,
    "description": "Suomen suosituin vihannes",
    "image": "bleu.jpg"
}

####################

DELETE http://localhost:5000/api/menuitems/d39